- generic [active] [ref=e1]:
  - link "Ir para o conteúdo principal" [ref=e2] [cursor=pointer]:
    - /url: "#main-content"
  - navigation [ref=e3]:
    - generic [ref=e4]:
      - link "Allos Allos Associação" [ref=e5] [cursor=pointer]:
        - /url: /
        - img "Allos" [ref=e6]
        - generic [ref=e7]:
          - text: Allos
          - generic [ref=e8]: Associação
      - generic [ref=e9]:
        - link "Sobre" [ref=e10] [cursor=pointer]:
          - /url: /sobre
        - link "Clínica" [ref=e11] [cursor=pointer]:
          - /url: /clinica
        - link "Formação" [ref=e12] [cursor=pointer]:
          - /url: /formacao
        - link "Projetos" [ref=e13] [cursor=pointer]:
          - /url: /projetos
      - generic [ref=e14]:
        - link "Quero me associar" [ref=e15] [cursor=pointer]:
          - /url: /processoseletivopsi
        - link "Agendar sessão" [ref=e16] [cursor=pointer]:
          - /url: https://allos.org.br/terapiasocial
  - main [ref=e17]:
    - generic [ref=e18]:
      - img
      - generic [ref=e19]:
        - heading "Nossos" [level=1] [ref=e21]
        - heading "Projetos" [level=1] [ref=e23]
        - generic [ref=e24]:
          - paragraph [ref=e25]: Iniciativas de impacto social em saúde mental, desenvolvidas em parceria com redes públicas e organizações comunitárias.
          - generic [ref=e29]: Saúde Pública · Comunidade
    - generic [ref=e31]:
      - generic [ref=e32]:
        - paragraph [ref=e33]: Iniciativas de impacto
        - heading "Psicologia que atravessa muros e chega onde mais precisa" [level=2] [ref=e34]
        - paragraph [ref=e35]: Operamos projetos clínicos estruturados em parceria com prefeituras, redes públicas e organizações comunitárias — sempre com supervisão técnica contínua, gestão digital por dados e foco em prevenção antes do adoecimento.
      - generic [ref=e36]:
        - generic [ref=e37]:
          - paragraph [ref=e38]: 1.230+
          - paragraph [ref=e39]: atendimentos em saúde pública
        - generic [ref=e40]:
          - paragraph [ref=e41]: "4"
          - paragraph [ref=e42]: projetos ativos em curso
        - generic [ref=e43]:
          - paragraph [ref=e44]: ~990
          - paragraph [ref=e45]: vidas diretamente impactadas
        - generic [ref=e46]:
          - paragraph [ref=e47]: "+90"
          - paragraph [ref=e48]: NPS médio das iniciativas
    - figure [ref=e51]:
      - generic [ref=e52]:
        - img "Casa Emanuel — registro do encontro" [ref=e53]
        - generic [ref=e54]:
          - generic [ref=e55]:
            - generic [ref=e56]: Casa Emanuel · em destaque
            - heading "Onde a tinta vira linguagem e o encontro vira clínica" [level=3] [ref=e57]
          - link "Ver projeto" [ref=e58] [cursor=pointer]:
            - /url: /projetos/casa-emanuel
            - text: Ver projeto
            - img [ref=e59]
        - generic [ref=e61]: Registro · 2024
    - generic [ref=e63]:
      - generic:
        - generic: Projetos ativos
      - generic [ref=e64]:
        - link [ref=e65] [cursor=pointer]:
          - /url: /projetos/prosam-bela-vista
          - article [ref=e66]:
            - generic [ref=e67]:
              - generic [ref=e69]:
                - generic [ref=e70]: Saúde Pública
                - generic [ref=e71]: Desde 2024
              - generic [ref=e73]:
                - text: Ver projeto
                - img [ref=e74]
            - generic [ref=e76]:
              - heading "ProSam Bela Vista de Minas" [level=3] [ref=e77]
              - paragraph [ref=e78]: Programa de saúde mental preventiva para servidores públicos municipais.
              - generic [ref=e79]:
                - img [ref=e80]
                - paragraph [ref=e83]: Bela Vista de Minas · MG
              - generic [ref=e84]:
                - paragraph [ref=e85]: 1230+ atendimentos · NPS +90
                - generic [ref=e86]:
                  - text: Detalhes
                  - img [ref=e87]
        - link [ref=e89] [cursor=pointer]:
          - /url: /projetos/prosam-materlandia
          - article [ref=e90]:
            - generic [ref=e91]:
              - generic [ref=e93]:
                - generic [ref=e94]: Saúde Pública
                - generic [ref=e95]: Desde 2026
              - generic [ref=e97]:
                - text: Ver projeto
                - img [ref=e98]
            - generic [ref=e100]:
              - heading "ProSam Materlândia" [level=3] [ref=e101]
              - paragraph [ref=e102]: Expansão do modelo ProSam para um novo município mineiro.
              - generic [ref=e103]:
                - img [ref=e104]
                - paragraph [ref=e107]: Materlândia · MG
              - generic [ref=e108]:
                - paragraph [ref=e109]: 121 atendimentos · NPS +75
                - generic [ref=e110]:
                  - text: Detalhes
                  - img [ref=e111]
        - link [ref=e113] [cursor=pointer]:
          - /url: /projetos/rama
          - article [ref=e114]:
            - generic [ref=e115]:
              - img "Rede RAMA" [ref=e116]
              - generic [ref=e117]:
                - generic [ref=e118]: Comunidade
                - generic [ref=e119]: Desde 2023
              - generic [ref=e121]:
                - text: Ver projeto
                - img [ref=e122]
            - generic [ref=e124]:
              - heading "Rede RAMA" [level=3] [ref=e125]
              - paragraph [ref=e126]: Grupos de apoio psicológico para mães em territórios vulneráveis.
              - generic [ref=e127]:
                - img [ref=e128]
                - paragraph [ref=e131]: Belo Horizonte · MG
              - generic [ref=e132]:
                - paragraph [ref=e133]: 50+ mães acompanhadas · 3 territórios
                - generic [ref=e134]:
                  - text: Detalhes
                  - img [ref=e135]
        - link [ref=e137] [cursor=pointer]:
          - /url: /projetos/casas
          - article [ref=e138]:
            - generic [ref=e139]:
              - generic [ref=e141]:
                - generic [ref=e142]: Comunidade
                - generic [ref=e143]: Novo em 2026
              - generic [ref=e145]:
                - text: Ver projeto
                - img [ref=e146]
            - generic [ref=e148]:
              - heading "As Casas" [level=3] [ref=e149]
              - paragraph [ref=e150]: Três comunidades de terapeutas, cada uma com uma sensibilidade clínica própria. Descubra a sua Casa.
              - generic [ref=e151]:
                - img [ref=e152]
                - paragraph [ref=e155]: Comunidade Allos
              - generic [ref=e156]:
                - paragraph [ref=e157]: 3 Casas · 12 Arquétipos · Teste interativo
                - generic [ref=e158]:
                  - text: Detalhes
                  - img [ref=e159]
        - link [ref=e161] [cursor=pointer]:
          - /url: /projetos/casa-emanuel
          - article [ref=e162]:
            - generic [ref=e163]:
              - img "Casa Emanuel" [ref=e164]
              - generic [ref=e165]:
                - generic [ref=e166]: Comunidade
                - generic [ref=e167]: Desde 2024
              - generic [ref=e169]:
                - text: Ver projeto
                - img [ref=e170]
            - generic [ref=e172]:
              - heading "Casa Emanuel" [level=3] [ref=e173]
              - paragraph [ref=e174]: Livre expressão e convivência inspiradas em Nise da Silveira. Encontros semanais com homens adultos em situação de vulnerabilidade.
              - generic [ref=e175]:
                - img [ref=e176]
                - paragraph [ref=e179]: Casa Emanuel
              - generic [ref=e180]:
                - paragraph [ref=e181]: Desde 2024 · Encontros semanais
                - generic [ref=e182]:
                  - text: Detalhes
                  - img [ref=e183]
    - generic [ref=e187]:
      - generic [ref=e188]:
        - paragraph [ref=e189]: Nossa abordagem
        - heading "Método clínico, gestão por dados e compromisso com o território" [level=3] [ref=e190]
        - generic [ref=e191]:
          - generic [ref=e192]:
            - img [ref=e194]
            - generic [ref=e196]:
              - heading "Seleção e supervisão rigorosas" [level=4] [ref=e197]
              - paragraph [ref=e198]: Terapeutas aprovados em banca técnica e supervisão clínica obrigatória em 100% dos atendimentos.
          - generic [ref=e199]:
            - img [ref=e201]
            - generic [ref=e204]:
              - heading "Gestão digital por dados" [level=4] [ref=e205]
              - paragraph [ref=e206]: "Plataforma Hamilton: prontuários, KPIs e desfechos clínicos rastreados em tempo real."
          - generic [ref=e207]:
            - img [ref=e209]
            - generic [ref=e212]:
              - heading "Atuação territorial" [level=4] [ref=e213]
              - paragraph [ref=e214]: Cuidado que chega onde a demanda existe — servidores públicos, comunidades e territórios vulneráveis.
      - generic [ref=e216]:
        - heading "Quer levar um projeto clínico para o seu município ou organização?" [level=3] [ref=e217]
        - paragraph [ref=e218]: Converse com a equipe da Allos e veja como podemos adaptar nossa metodologia à realidade do seu contexto.
        - link "Falar com a Allos" [ref=e219] [cursor=pointer]:
          - /url: mailto:institucional@allos.org.br
          - text: Falar com a Allos
          - img [ref=e220]
        - paragraph [ref=e222]: institucional@allos.org.br
  - contentinfo [ref=e223]:
    - generic [ref=e224]:
      - generic [ref=e225]:
        - generic [ref=e226]:
          - generic [ref=e227]:
            - img "Allos" [ref=e228]
            - generic [ref=e229]: Allos
          - paragraph [ref=e230]: Psicologia clínica com excelência.
        - generic [ref=e231]:
          - heading "Endereço" [level=4] [ref=e232]
          - generic [ref=e233]:
            - text: Rua Rio Negro, 1048
            - text: Belo Horizonte – MG
            - text: "CEP: 30.431-058"
        - generic [ref=e234]:
          - heading "Contato" [level=4] [ref=e235]
          - generic [ref=e236]:
            - link "suporte@allos.org.br" [ref=e237] [cursor=pointer]:
              - /url: mailto:suporte@allos.org.br
            - link "+55 31 98757-7892" [ref=e238] [cursor=pointer]:
              - /url: https://wa.me/5531987577892
        - generic [ref=e239]:
          - heading "Links" [level=4] [ref=e240]
          - navigation [ref=e241]:
            - link "FAQ" [ref=e242] [cursor=pointer]:
              - /url: /faq
            - link "Sobre a Allos" [ref=e243] [cursor=pointer]:
              - /url: /sobre
            - link "Clínica Social" [ref=e244] [cursor=pointer]:
              - /url: /clinica
            - link "Formação Geral" [ref=e245] [cursor=pointer]:
              - /url: /formacao-geral
            - link "Processo Seletivo" [ref=e246] [cursor=pointer]:
              - /url: /processoseletivopsi
      - generic [ref=e247]:
        - link "Instagram" [ref=e248] [cursor=pointer]:
          - /url: https://www.instagram.com/associacaoallos/
          - img [ref=e249]
        - link "YouTube" [ref=e251] [cursor=pointer]:
          - /url: https://www.youtube.com/@associacaoallos
          - img [ref=e252]
        - link "Avalie-nos no Google" [ref=e254] [cursor=pointer]:
          - /url: https://search.google.com/local/writereview?placeid=ChIJRU1omzaXpgARA4UFQLEIq4g
          - img [ref=e255]
          - generic [ref=e260]: Avalie-nos no Google
      - generic [ref=e261]:
        - paragraph [ref=e262]: © 2026 Associação Allos. Todos os direitos reservados.
        - paragraph [ref=e263]: Desenvolvido com ♥ em Belo Horizonte
  - alert [ref=e264]